[project]
name = "cheapchocolate"
version = "0.6.0"
license = "MIT"
description = "CheapChocolate is an simple imap client to receive you daily email."
readme = "README.md"
authors = [
    { name = "Cesar Cardoso", email = "hello@cesarcardoso.cc" }
]
requires-python = ">=3.11"
dependencies = [
    "conveoconfi>=0.1.0",
    "dotenv>=0.9.9",
    "pyyaml>=6.0.3",
]

[dependency-groups]
dev = [
    "coverage>=7.12.0",
    "pytest>=9.0.1",
]

[project.urls]
Repository = "https://github.com/bouli/cheapchocolate"
Changelog = "https://github.com/bouli/cheapchocolate/releases/latest"

[project.scripts]
cheapchocolate = "cheapchocolate:main"


[build-system]
requires = ["uv_build>=0.9.17,<0.10.0"]
build-backend = "uv_build"

[tool.bumpversion]
tag = true
tag_name = "v{new_version}"
pre_commit_hooks = ["printf \"# CHANGELOG\n\n\" > CHANGELOG.md && git log v0.6.0..HEAD --format=\"* %h %s (%an)\" >> CHANGELOG.md", "git add CHANGELOG.md", "uvx isort ./src", "uvx black ./src", "git add src","uv sync --upgrade", "git add uv.lock"]
commit = true

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'v{current_version}..HEAD'
replace = 'v{new_version}..HEAD'

[[tool.bumpversion.files]]
filename = "README.md"

[[tool.bumpversion.files]]
filename = "Makefile"

[[tool.bumpversion.files]]
filename = "src/cheapchocolate/__init__.py"
